version: '3.3'
services:
  docker:
    container_name: jenkins-docker
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - './jenkins-docker-certs:/certs/client'
      - './jenkins-data:/var/jenkins_home'
    ports:
      - '2376:2376'
    image: 'docker:dind'
    command: '--storage-driver overlay2'

  jenkins:
    build:
      context: .
    restart: always
    environment:
      - 'DOCKER_HOST=tcp://docker:2376'
      - 'DOCKER_CERT_PATH=/certs/client'
      - 'DOCKER_TLS_VERIFY=1'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - './jenkins-docker-certs:/certs/client:ro'
      - './jenkins-data:/var/jenkins_home'
